{% set version = "0.9.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-canyonb
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/fair-ease/CANYON-B/archive/refs/tags/v.{{ version }}.tar.gz
  sha256: b183c08f3b82df85c16ee69fd24976280e15dcf8cb3dbc111abbabb544b98494

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/ 

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]  
  host:
    - r-base >=4.1
    - r-mgcv
    - r-seacarb
    - r-tibble
  run:
    - r-base >=4.1
    - r-mgcv
    - r-seacarb
    - r-tibble

test:
  commands:
    - $R -e "library('canyonb')"           # [not win]

about:
  home: https://github.com/HCBScienceProducts/CANYON-B/tree/v0.9
  license: GPL-3.0-or-later 
  license_file: LICENSE
  license_family: GPL
  summary: CANYON-B method published in Bittig et al. (2018). An alternative to static climatologies Robust estimation of open ocean CO2 variables and nutrient concentrations from T, S and O2 data using Bayesian neural networks. Front. Mar. Sci. subm. http://dx.doi.org/10.3389/fmars.2018.xxxxx.

extra:
  recipe-maintainers:
    - conda-forge/r
    - Marie59
